### ISSUE TITLE
Issue on Khalti Integration not working while booking trips.

### ISSUE THREAD

**Issue by Shreejal-khatri** [SamipMaharjan/Bus-Ticket-Booking#4]
![image](https://github.com/SamipMaharjan/Bus-Ticket-Booking/assets/127380069/942ee70e-074e-472b-b498-c730a2c60cb9)

**Fix the button on the bus ticket page where, when a user clicks on book button they get redirected to an error page by Khalti.**

**Comment by SamipMaharjan** [comment]
The issue is resolved in the latest commit as the application now uses fresh links from khalti's API instead of hardcoded ones.
